### ISSUE TITLE
Script fails on :fill!

### ISSUE THREAD

**Issue by ghost** [memiah/crison#12]
It fails when it's only a fill, without submit

**Comment by ghost** [comment]
`[
{:url! "http://www.counselling-directory.org.uk" :screenshot "on-url"}
​
{:fill! {:text! "Camberley" :tag :input :placeholder "Enter your postcode, town or county"} :screenshot "on-fill" :source "on-fill"}
​
; {:click! {:value "Search" :class "homepage-search-submit"} :screenshot "main-search"}
​
]`

**Comment by rossm-memiah** [comment]
fixed in 0.5.0 - at least for the markup on pages I've tested
