### ISSUE TITLE
Flexible screenshot capability

### ISSUE THREAD

**Issue by CarlMemiah** [memiah/crison#8]
Enable taking a screenshot with every test block.

Block = a combination of drives and assertions

**Comment by paulmaunders** [comment]
It would also be useful to be able to take a screenshot at a specific time or event, e.g. after the DomContentLoaded event is triggered. This is to help spot the "Flash of Unstyled Content" problem that we are getting.

**Comment by rossajmcd** [comment]
The per block feedback is definitely possible and I suspect the specific event option is also doable... I can certainly wait for element 'presence' etc... I will have a look into it soon.

Thanks for the feedback all.

**Comment by rossm-memiah** [comment]
Screenshots are now configurable per 'directive' i.e. state changes like :click!, :url! etc.

**Comment by rossm-memiah** [comment]
I will split out your comment here into a new item Paul as I am just looking into something to help Barna with his 'Flash of Unstyled Content' problem.

**Comment by rossm-memiah** [comment]
done
